package com.github.alexthe666.alexsmobs.client.render;

import com.github.alexthe666.alexsmobs.misc.AMCompat;

import com.github.alexthe666.alexsmobs.entity.EntityVoidPortal;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import org.joml.Matrix3f;
import org.joml.Matrix4f;

public class RenderVoidPortal extends EntityRenderer<EntityVoidPortal> {
    private static final ResourceLocation TEXTURE_0 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/portal_idle_0.png");
    private static final ResourceLocation TEXTURE_1 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/portal_idle_1.png");
    private static final ResourceLocation TEXTURE_2 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/portal_idle_2.png");
    private static final ResourceLocation TEXTURE_SHATTERED_0 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_idle_0.png");
    private static final ResourceLocation TEXTURE_SHATTERED_1 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_idle_1.png");
    private static final ResourceLocation TEXTURE_SHATTERED_2 = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_idle_2.png");
    private static final ResourceLocation[] TEXTURE_PROGRESS = new ResourceLocation[10];
    private static final ResourceLocation[] TEXTURE_SHATTERED_PROGRESS = new ResourceLocation[10];
    private static final int NOISE_VARIANTS = 4;
    // Static noise pre-baked into each shattered frame (4 noise variants apiece), generated by
    // scripts/bake_static_textures.py. Only drawn on >=1.21.5, where the two-pass EQUAL-depth static
    // overlay no longer exists and the bare mask is a black disc — see AMRenderTypes (#90, #53).
    private static final ResourceLocation[][] TEXTURE_SHATTERED_IDLE_STATIC = new ResourceLocation[3][NOISE_VARIANTS];
    private static final ResourceLocation[][] TEXTURE_SHATTERED_PROGRESS_STATIC = new ResourceLocation[10][NOISE_VARIANTS];
    static {
        for (int v = 0; v < NOISE_VARIANTS; v++) {
            for (int i = 0; i < 3; i++) {
                TEXTURE_SHATTERED_IDLE_STATIC[i][v] = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_idle_" + i + "_static_" + v + ".png");
            }
            for (int i = 0; i < 10; i++) {
                TEXTURE_SHATTERED_PROGRESS_STATIC[i][v] = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_grow_" + i + "_static_" + v + ".png");
            }
        }
    }
    public RenderVoidPortal(EntityRendererProvider.Context renderManagerIn) {
        super(renderManagerIn);
        for(int i = 0; i < 10; i++){
            TEXTURE_PROGRESS[i] = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/portal_grow_" + i + ".png");
            TEXTURE_SHATTERED_PROGRESS[i] = AMCompat.rl("alexsmobs:textures/entity/void_worm/portal/shattered/portal_grow_" + i + ".png");
        }
    }

    public void render(EntityVoidPortal entityIn, float entityYaw, float partialTicks, PoseStack matrixStackIn, MultiBufferSource bufferIn, int packedLightIn) {
        matrixStackIn.pushPose();
        matrixStackIn.mulPose(entityIn.getAttachmentFacing().getOpposite().getRotation());
        matrixStackIn.translate(0.5D, 0, 0.5D);
        matrixStackIn.scale(2F, 2F, 2F);
        renderPortal(entityIn, matrixStackIn, bufferIn, false);
        if(entityIn.isShattered()){
            float off = 0.01F;
            matrixStackIn.pushPose();
            matrixStackIn.translate(0F, off, 0F);
            renderPortal(entityIn, matrixStackIn, bufferIn, true);
            matrixStackIn.popPose();
            matrixStackIn.pushPose();
            matrixStackIn.translate(0F, -off, 0F);
            renderPortal(entityIn, matrixStackIn, bufferIn, true);
            matrixStackIn.popPose();
        }
        matrixStackIn.popPose();
        super.render(entityIn, entityYaw, partialTicks, matrixStackIn, bufferIn, packedLightIn);
    }

    private void renderPortal(EntityVoidPortal entityIn, PoseStack matrixStackIn, MultiBufferSource bufferIn, boolean shattered){
        ResourceLocation tex;
        ResourceLocation baked;
        final int variant = Math.floorMod(entityIn.tickCount / 2, NOISE_VARIANTS);
        if(entityIn.getLifespan() < 20){
            int frame = Mth.clamp((int) ((entityIn.getLifespan() * 0.5F) % 10), 0, 9);
            tex = getGrowingTexture(frame, shattered);
            baked = TEXTURE_SHATTERED_PROGRESS_STATIC[frame][variant];
        }else if(entityIn.tickCount < 20){
            int frame = Mth.clamp((int) ((entityIn.tickCount * 0.5F) % 10), 0, 9);
            tex = getGrowingTexture(frame, shattered);
            baked = TEXTURE_SHATTERED_PROGRESS_STATIC[frame][variant];
        }else{
            int age = entityIn.tickCount % 9;
            tex = getIdleTexture(age, shattered);
            baked = TEXTURE_SHATTERED_IDLE_STATIC[idleIndex(age)][variant];
        }
        if (shattered) {
            // The shattered overlay is a *mask* site, not a geometry one: the texture is pure black
            // with an alpha cut-out, and everything visible about it came from the STATIC_PORTAL pass
            // drawn over it at EQUAL depth. Dropping that pass leaves a black disc (#90), so >=1.21.5
            // draws the pre-baked static instead. entityCutoutNoCull is upstream's spelling for the
            // <1.21.5 arm and has to be preserved exactly.
            AMRenderTypes.renderStaticMasked(bufferIn, AMRenderTypes.STATIC_PORTAL, RenderType.entityCutoutNoCull(tex), baked,
                    ivertexbuilder -> renderArc(matrixStackIn, ivertexbuilder));
        } else {
            renderArc(matrixStackIn, bufferIn.getBuffer(AMRenderTypes.getFullBright(tex)));
        }
    }

    private static int idleIndex(int age) {
        if (age < 3) {
            return 0;
        } else if (age < 6) {
            return 1;
        } else if (age < 10) {
            return 2;
        } else {
            return 0;
        }
    }
    private void renderArc(PoseStack matrixStackIn, VertexConsumer ivertexbuilder) {
        matrixStackIn.pushPose();
        PoseStack.Pose lvt_19_1_ = matrixStackIn.last();
        Matrix4f lvt_20_1_ = lvt_19_1_.pose();
        Matrix3f lvt_21_1_ = lvt_19_1_.normal();
        this.drawVertex(lvt_20_1_, lvt_21_1_, ivertexbuilder, -1, 0, -1, 0, 0, 1, 0, 1, 240);
        this.drawVertex(lvt_20_1_, lvt_21_1_, ivertexbuilder, -1, 0, 1, 0, 1, 1, 0, 1, 240);
        this.drawVertex(lvt_20_1_, lvt_21_1_, ivertexbuilder, 1, 0, 1, 1, 1, 1, 0, 1, 240);
        this.drawVertex(lvt_20_1_, lvt_21_1_, ivertexbuilder, 1, 0, -1, 1, 0, 1, 0, 1, 240);
        matrixStackIn.popPose();
    }

    @Override
    public ResourceLocation getTextureLocation(EntityVoidPortal entity) {
        return TEXTURE_0;
    }


    public void drawVertex(Matrix4f p_229039_1_, Matrix3f p_229039_2_, VertexConsumer p_229039_3_, int p_229039_4_, int p_229039_5_, int p_229039_6_, float p_229039_7_, float p_229039_8_, int p_229039_9_, int p_229039_10_, int p_229039_11_, int p_229039_12_) {
        com.github.alexthe666.alexsmobs.client.render.AMVertex.normal(p_229039_3_.vertex(p_229039_1_, (float) p_229039_4_, (float) p_229039_5_, (float) p_229039_6_).color(255, 255, 255, 255).uv(p_229039_7_, p_229039_8_).overlayCoords(OverlayTexture.NO_OVERLAY).uv2(p_229039_12_), p_229039_2_, (float) p_229039_9_, (float) p_229039_11_, (float) p_229039_10_).endVertex();
    }


    public ResourceLocation getIdleTexture(int age, boolean shattered) {
        switch (idleIndex(age)) {
            case 1:
                return shattered ? TEXTURE_SHATTERED_1 : TEXTURE_1;
            case 2:
                return shattered ? TEXTURE_SHATTERED_2 : TEXTURE_2;
            default:
                return shattered ? TEXTURE_SHATTERED_0 : TEXTURE_0;
        }
    }

    public ResourceLocation getGrowingTexture(int age, boolean shattered) {
        return shattered ? TEXTURE_SHATTERED_PROGRESS[Mth.clamp(age, 0, 9)] : TEXTURE_PROGRESS[Mth.clamp(age, 0, 9)];
    }
}
