package com.github.alexthe666.alexsmobs.config;

import codx.codxlib.api.settings.CodxSettings;
import com.google.common.collect.Lists;

import java.util.List;

public class CommonConfig {

    public final CodxSettings.DoubleValue lavaOpacity;
    public final CodxSettings.BooleanValue shadersCompat;
    public final CodxSettings.BooleanValue neutralBoneSerpents;
    public final CodxSettings.BooleanValue lavaBottleEnabled;
    public final CodxSettings.BooleanValue spidersAttackFlies;
    public final CodxSettings.BooleanValue wolvesAttackMoose;
    public final CodxSettings.BooleanValue polarBearsAttackSeals;
    public final CodxSettings.BooleanValue catsAndFoxesAttackJerboas;
    public final CodxSettings.BooleanValue dolphinsAttackFlyingFish;
    public final CodxSettings.BooleanValue bananasDropFromLeaves;
    public final CodxSettings.IntValue bananaChance;
    public final CodxSettings.IntValue grizzlyBearSpawnWeight;
    public final CodxSettings.IntValue grizzlyBearSpawnRolls;
    public final CodxSettings.IntValue roadrunnerSpawnWeight;
    public final CodxSettings.IntValue roadrunnerSpawnRolls;
    public final CodxSettings.IntValue boneSerpentSpawnWeight;
    public final CodxSettings.IntValue boneSeprentSpawnRolls;
    public final CodxSettings.IntValue gazelleSpawnWeight;
    public final CodxSettings.IntValue gazelleSpawnRolls;
    public final CodxSettings.IntValue crocodileSpawnWeight;
    public final CodxSettings.IntValue crocSpawnRolls;
    public final CodxSettings.IntValue flySpawnWeight;
    public final CodxSettings.IntValue flySpawnRolls;
    public final CodxSettings.IntValue hummingbirdSpawnWeight;
    public final CodxSettings.IntValue hummingbirdSpawnRolls;
    public final CodxSettings.IntValue orcaSpawnWeight;
    public final CodxSettings.IntValue orcaSpawnRolls;
    public final CodxSettings.IntValue sunbirdSpawnWeight;
    public final CodxSettings.IntValue sunbirdSpawnRolls;
    public final CodxSettings.IntValue gorillaSpawnWeight;
    public final CodxSettings.IntValue gorillaSpawnRolls;
    public final CodxSettings.IntValue crimsonMosquitoSpawnWeight;
    public final CodxSettings.IntValue crimsonMosquitoSpawnRolls;
    public final CodxSettings.IntValue rattlesnakeSpawnWeight;
    public final CodxSettings.IntValue rattlesnakeSpawnRolls;
    public final CodxSettings.IntValue endergradeSpawnWeight;
    public final CodxSettings.IntValue endergradeSpawnRolls;
    public final CodxSettings.IntValue hammerheadSharkSpawnWeight;
    public final CodxSettings.IntValue hammerheadSharkSpawnRolls;
    public final CodxSettings.IntValue lobsterSpawnWeight;
    public final CodxSettings.IntValue lobsterSpawnRolls;
    public final CodxSettings.IntValue komodoDragonSpawnWeight;
    public final CodxSettings.IntValue komodoDragonSpawnRolls;
    public final CodxSettings.IntValue capuchinMonkeySpawnWeight;
    public final CodxSettings.IntValue capuchinMonkeySpawnRolls;
    public final CodxSettings.IntValue caveCentipedeSpawnWeight;
    public final CodxSettings.IntValue caveCentipedeSpawnRolls;
    public final CodxSettings.IntValue caveCentipedeSpawnHeight;
    public final CodxSettings.IntValue warpedToadSpawnWeight;
    public final CodxSettings.IntValue warpedToadSpawnRolls;
    public final CodxSettings.IntValue mooseSpawnWeight;
    public final CodxSettings.IntValue mooseSpawnRolls;
    public final CodxSettings.IntValue mimicubeSpawnWeight;
    public final CodxSettings.IntValue mimicubeSpawnRolls;
    public final CodxSettings.IntValue raccoonSpawnWeight;
    public final CodxSettings.IntValue raccoonSpawnRolls;
    public final CodxSettings.IntValue blobfishSpawnWeight;
    public final CodxSettings.IntValue blobfishSpawnRolls;
    public final CodxSettings.IntValue blobfishSpawnHeight;
    public final CodxSettings.IntValue sealSpawnWeight;
    public final CodxSettings.IntValue sealSpawnRolls;
    public final CodxSettings.IntValue cockroachSpawnWeight;
    public final CodxSettings.IntValue cockroachSpawnRolls;
    public final CodxSettings.IntValue shoebillSpawnWeight;
    public final CodxSettings.IntValue shoebillSpawnRolls;
    public final CodxSettings.IntValue elephantSpawnWeight;
    public final CodxSettings.IntValue elephantSpawnRolls;
    public final CodxSettings.IntValue soulVultureSpawnWeight;
    public final CodxSettings.IntValue soulVultureSpawnRolls;
    public final CodxSettings.IntValue snowLeopardSpawnWeight;
    public final CodxSettings.IntValue snowLeopardSpawnRolls;
    public final CodxSettings.IntValue spectreSpawnWeight;
    public final CodxSettings.IntValue spectreSpawnRolls;
    public final CodxSettings.IntValue crowSpawnWeight;
    public final CodxSettings.IntValue crowSpawnRolls;
    public final CodxSettings.IntValue alligatorSnappingTurtleSpawnWeight;
    public final CodxSettings.IntValue alligatorSnappingTurtleSpawnRolls;
    public final CodxSettings.IntValue mungusSpawnWeight;
    public final CodxSettings.IntValue mungusSpawnRolls;
    public final CodxSettings.IntValue mantisShrimpSpawnWeight;
    public final CodxSettings.IntValue mantisShrimpSpawnRolls;
    public final CodxSettings.IntValue gusterSpawnWeight;
    public final CodxSettings.IntValue gusterSpawnRolls;
    public final CodxSettings.IntValue warpedMoscoSpawnWeight;
    public final CodxSettings.IntValue warpedMoscoSpawnRolls;
    public final CodxSettings.IntValue straddlerSpawnWeight;
    public final CodxSettings.IntValue straddlerSpawnRolls;
    public final CodxSettings.IntValue stradpoleSpawnWeight;
    public final CodxSettings.IntValue stradpoleSpawnRolls;
    public final CodxSettings.IntValue emuSpawnWeight;
    public final CodxSettings.IntValue emuSpawnRolls;
    public final CodxSettings.IntValue platypusSpawnWeight;
    public final CodxSettings.IntValue platypusSpawnRolls;
    public final CodxSettings.IntValue dropbearSpawnWeight;
    public final CodxSettings.IntValue dropbearSpawnRolls;
    public final CodxSettings.IntValue tasmanianDevilSpawnWeight;
    public final CodxSettings.IntValue tasmanianDevilSpawnRolls;
    public final CodxSettings.IntValue kangarooSpawnWeight;
    public final CodxSettings.IntValue kangarooSpawnRolls;
    public final CodxSettings.IntValue cachalotWhaleSpawnWeight;
    public final CodxSettings.IntValue cachalotWhaleSpawnRolls;
    public final CodxSettings.IntValue enderiophageSpawnWeight;
    public final CodxSettings.IntValue enderiophageSpawnRolls;
    public final CodxSettings.IntValue baldEagleSpawnWeight;
    public final CodxSettings.IntValue baldEagleSpawnRolls;
    public final CodxSettings.IntValue tigerSpawnWeight;
    public final CodxSettings.IntValue tigerSpawnRolls;
    public final CodxSettings.IntValue tarantulaHawkSpawnWeight;
    public final CodxSettings.IntValue tarantulaHawkSpawnRolls;
    public final CodxSettings.IntValue voidWormSpawnWeight;
    public final CodxSettings.IntValue voidWormSpawnRolls;
    public final CodxSettings.IntValue frilledSharkSpawnWeight;
    public final CodxSettings.IntValue frilledSharkSpawnRolls;
    public final CodxSettings.IntValue mimicOctopusSpawnWeight;
    public final CodxSettings.IntValue mimicOctopusSpawnRolls;
    public final CodxSettings.IntValue seagullSpawnWeight;
    public final CodxSettings.IntValue seagullSpawnRolls;
    public final CodxSettings.IntValue froststalkerSpawnWeight;
    public final CodxSettings.IntValue froststalkerSpawnRolls;
    public final CodxSettings.IntValue tusklinSpawnWeight;
    public final CodxSettings.IntValue tusklinSpawnRolls;
    public final CodxSettings.IntValue laviathanSpawnWeight;
    public final CodxSettings.IntValue laviathanSpawnRolls;
    public final CodxSettings.IntValue cosmawSpawnWeight;
    public final CodxSettings.IntValue cosmawSpawnRolls;
    public final CodxSettings.IntValue toucanSpawnWeight;
    public final CodxSettings.IntValue toucanSpawnRolls;
    public final CodxSettings.IntValue manedWolfSpawnWeight;
    public final CodxSettings.IntValue manedWolfSpawnRolls;
    public final CodxSettings.IntValue anacondaSpawnWeight;
    public final CodxSettings.IntValue anacondaSpawnRolls;
    public final CodxSettings.IntValue anteaterSpawnWeight;
    public final CodxSettings.IntValue anteaterSpawnRolls;
    public final CodxSettings.IntValue rockyRollerSpawnWeight;
    public final CodxSettings.IntValue rockyRollerSpawnRolls;
    public final CodxSettings.IntValue flutterSpawnWeight;
    public final CodxSettings.IntValue flutterSpawnRolls;
    public final CodxSettings.IntValue geladaMonkeySpawnWeight;
    public final CodxSettings.IntValue geladaMonkeySpawnRolls;
    public final CodxSettings.IntValue geladaMonkeySpawnHeight;
    public final CodxSettings.IntValue jerboaSpawnRolls;
    public final CodxSettings.IntValue jerboaSpawnWeight;
    public final CodxSettings.IntValue terrapinSpawnRolls;
    public final CodxSettings.IntValue terrapinSpawnWeight;
    public final CodxSettings.IntValue combJellySpawnRolls;
    public final CodxSettings.IntValue combJellySpawnWeight;
    public final CodxSettings.IntValue cosmicCodSpawnRolls;
    public final CodxSettings.IntValue cosmicCodSpawnWeight;
    public final CodxSettings.IntValue bunfungusSpawnWeight;
    public final CodxSettings.IntValue bunfungusSpawnRolls;
    public final CodxSettings.IntValue bisonSpawnWeight;
    public final CodxSettings.IntValue bisonSpawnRolls;
    public final CodxSettings.IntValue giantSquidSpawnWeight;
    public final CodxSettings.IntValue giantSquidSpawnRolls;
    public final CodxSettings.IntValue devilsHolePupfishSpawnWeight;
    public final CodxSettings.IntValue devilsHolePupfishSpawnRolls;
    public final CodxSettings.IntValue catfishSpawnWeight;
    public final CodxSettings.IntValue catfishSpawnRolls;
    public final CodxSettings.IntValue flyingFishSpawnWeight;
    public final CodxSettings.IntValue flyingFishSpawnRolls;
    public final CodxSettings.IntValue skelewagSpawnWeight;
    public final CodxSettings.IntValue skelewagSpawnRolls;
    public final CodxSettings.IntValue rainFrogSpawnWeight;
    public final CodxSettings.IntValue rainFrogSpawnRolls;
    public final CodxSettings.IntValue potooSpawnWeight;
    public final CodxSettings.IntValue potooSpawnRolls;
    public final CodxSettings.IntValue mudskipperSpawnWeight;
    public final CodxSettings.IntValue mudskipperSpawnRolls;
    public final CodxSettings.IntValue rhinocerosSpawnWeight;
    public final CodxSettings.IntValue rhinocerosSpawnRolls;
    public final CodxSettings.IntValue sugarGliderSpawnWeight;
    public final CodxSettings.IntValue sugarGliderSpawnRolls;
    public final CodxSettings.IntValue farseerSpawnWeight;
    public final CodxSettings.IntValue farseerSpawnRolls;
    public final CodxSettings.IntValue skreecherSpawnWeight;
    public final CodxSettings.IntValue skreecherSpawnRolls;
    public final CodxSettings.IntValue underminerSpawnWeight;
    public final CodxSettings.IntValue underminerSpawnRolls;
    public final CodxSettings.IntValue murmurSpawnWeight;
    public final CodxSettings.IntValue murmurSpawnRolls;
    public final CodxSettings.IntValue murmurSpawnHeight;
    public final CodxSettings.IntValue skunkSpawnWeight;
    public final CodxSettings.IntValue skunkSpawnRolls;
    public final CodxSettings.IntValue bananaSlugSpawnWeight;
    public final CodxSettings.IntValue bananaSlugSpawnRolls;
    public final CodxSettings.IntValue blueJaySpawnWeight;
    public final CodxSettings.IntValue blueJaySpawnRolls;
   public final CodxSettings.IntValue caimanSpawnWeight;
    public final CodxSettings.IntValue caimanSpawnRolls;
    public final CodxSettings.IntValue triopsSpawnWeight;
    public final CodxSettings.IntValue triopsSpawnRolls;
    public final CodxSettings.BooleanValue giveBookOnStartup;
    public final CodxSettings.BooleanValue mimicubeSpawnInEndCity;
    public final CodxSettings.BooleanValue mimicreamRepair;
    public final CodxSettings.ConfigValue<List<? extends String>> mimicreamBlacklist;
    public final CodxSettings.BooleanValue raccoonStealFromChests;
    public final CodxSettings.BooleanValue crowsStealCrops;
    public final CodxSettings.BooleanValue fishOilMeme;
    public final CodxSettings.BooleanValue soulVultureSpawnOnFossil;
    public final CodxSettings.BooleanValue acaciaBlossomsDropFromLeaves;
    public final CodxSettings.IntValue acaciaBlossomChance;
    public final CodxSettings.BooleanValue wanderingTraderOffers;
    public final CodxSettings.IntValue mungusBiomeTransformationType;
    public final CodxSettings.ConfigValue<List<? extends String>> mungusBiomeMatches;
    public CodxSettings.BooleanValue limitGusterSpawnsToWeather;
    public CodxSettings.BooleanValue warpedMoscoTransformation;
    public final CodxSettings.ConfigValue<List<? extends String>> warpedMoscoMobTriggers;
    public final CodxSettings.BooleanValue straddleboardEnchants;
    public final CodxSettings.IntValue straddleboardBaseColor;
    public final CodxSettings.IntValue straddleboardPanelColor;
    public final CodxSettings.BooleanValue emuTargetSkeletons;
    public final CodxSettings.DoubleValue emuPantsDodgeChance;
    public final CodxSettings.DoubleValue leafcutterAntFungusGrowChance;
    public final CodxSettings.IntValue leafcutterAntRepopulateFeedings;
    public final CodxSettings.IntValue leafcutterAntColonySize;
    public final CodxSettings.DoubleValue leafcutterAntBreakLeavesChance;
    public final CodxSettings.BooleanValue beachedCachalotWhales;
    public final CodxSettings.BooleanValue cachalotDestruction;
    public final CodxSettings.DoubleValue cachalotVolume;
    public final CodxSettings.IntValue beachedCachalotWhaleSpawnChance;
    public final CodxSettings.IntValue beachedCachalotWhaleSpawnDelay;
    public final CodxSettings.DoubleValue leafcutterAnthillSpawnChance;
    public final CodxSettings.BooleanValue falconryTeleportsBack;
    public final CodxSettings.BooleanValue fireproofTarantulaHawk;
    public final CodxSettings.BooleanValue voidWormSummonable;
    public final CodxSettings.ConfigValue<List<? extends String>> voidWormSpawnDimensions;
    public final CodxSettings.DoubleValue voidWormDamageModifier;
    public final CodxSettings.DoubleValue voidWormMaxHealth;
    public final CodxSettings.BooleanValue seagullStealing;
    public final CodxSettings.ConfigValue<List<? extends String>> seagullStealingBlacklist;
    public final CodxSettings.BooleanValue clingingFlipEffect;
    public final CodxSettings.DoubleValue tusklinShoesBarteringChance;
    public final CodxSettings.DoubleValue rainbowGlassFidelity;
    public CodxSettings.BooleanValue bunfungusTransformation;
    public CodxSettings.BooleanValue restrictPupfishSpawns;
    public CodxSettings.IntValue pupfishChunkSpawnDistance;
    public CodxSettings.BooleanValue restrictSkelewagSpawns;
    public CodxSettings.BooleanValue restrictFarseerSpawns;
    public CodxSettings.BooleanValue restrictUnderminerSpawns;
    public CodxSettings.IntValue farseerBorderSpawnDistance;
    public CodxSettings.BooleanValue superSecretSettings;
    public CodxSettings.BooleanValue addLootToChests;
    public final CodxSettings.ConfigValue<List<? extends String>> transmutationBlacklist;
    public CodxSettings.BooleanValue limitTransmutingToLootTables;
    public CodxSettings.BooleanValue transmutingTableExplodes;
    public CodxSettings.IntValue transmutingExperienceCost;
    public CodxSettings.DoubleValue transmutingWeightAddStep;
    public CodxSettings.DoubleValue transmutingWeightRemoveStep;
    public CodxSettings.DoubleValue underminerDisappearDistance;
    public final CodxSettings.BooleanValue skreechersSummonWarden;
    public CodxSettings.IntValue pathfindingThreads;

    public CommonConfig(final CodxSettings.Builder builder) {
        builder.push("general");
        giveBookOnStartup = buildBoolean(builder, "giveBookOnStartup", "all", true, "Whether all players should get an Animal Dictionary when joining the world for the first time.");
        lavaOpacity = buildDouble(builder, "lavaVisionOpacity", "all", 0.65D, 0.01D, 1D, "Lava Opacity for the Lava Vision Potion.");
        shadersCompat = buildBoolean(builder, "shadersCompat", "all", false, "Whether to disable certain aspects of the Lava Vision Potion. Enable if issues with shaders persist.");
        bananasDropFromLeaves = buildBoolean(builder, "bananasDropFromLeaves", "all", true, "Whether bananas should drop from blocks tagged with #alexsmobs:drops_bananas");
        bananaChance = buildInt(builder, "bananaChance", "all", AMConfig.bananaChance, 0, Integer.MAX_VALUE, "1 out of this number chance for leaves to drop a banana when broken. Fortune is automatically factored in");
        spidersAttackFlies = buildBoolean(builder, "spidersAttackFlies", "all", true, "Whether spiders should target fly mobs.");
        wolvesAttackMoose = buildBoolean(builder, "wolvesAttackMoose", "all", true, "Whether wolves should target moose mobs.");
        polarBearsAttackSeals = buildBoolean(builder, "polarBearsAttackSeals", "all", true, "Whether polar bears should target seal mobs.");
        catsAndFoxesAttackJerboas = buildBoolean(builder, "catsAndFoxesAttackJerboas", "all", true, "Whether cats, ocelots and foxes should target jerboa mobs.");
        dolphinsAttackFlyingFish = buildBoolean(builder, "dolphinsAttackFlyingFish", "all", true, "Whether dolphins should target flying fish mobs.");
        lavaBottleEnabled = buildBoolean(builder, "lavaBottleEnabled", "all", true, "Whether lava can be bottled with a right click of a glass bottle.");
        neutralBoneSerpents = buildBoolean(builder, "neutralBoneSerpents", "all", false, "Whether bone serpents are neutral or hostile.");
        mimicubeSpawnInEndCity = buildBoolean(builder, "mimicubeSpawnInEndCity", "all", true, "Whether mimicubes spawns should be restricted solely to the end city structure or to whatever biome is specified in their respective biome config.");
        mimicreamRepair = buildBoolean(builder, "mimicreamRepair", "all", true, "Whether mimicream can be used to duplicate items.");
        mimicreamBlacklist = builder.comment("Blacklist for items that mimicream cannot make a copy of. Ex: \"minecraft:stone_sword\", \"alexsmobs:blood_sprayer\"").defineList("mimicreamBlacklist", Lists.newArrayList("alexsmobs:blood_sprayer", "alexsmobs:hemolymph_blaster"), o -> o instanceof String);
        raccoonStealFromChests = buildBoolean(builder, "raccoonStealFromChests", "all", true, "Whether wild raccoons steal food from chests.");
        crowsStealCrops = buildBoolean(builder, "crowsStealCrops", "all", true, "Whether wild crows steal crops from farmland.");
        fishOilMeme = buildBoolean(builder, "fishOilMeme", "all", true, "Whether fish oil gives players a special levitation effect.");
        soulVultureSpawnOnFossil = buildBoolean(builder, "soulVultureSpawnOnFossil", "all", true, "Whether soul vulture spawns should be restricted solely to the nether fossil structure or to whatever biome is specified in their respective biome config.");
        acaciaBlossomsDropFromLeaves = buildBoolean(builder, "acaciaBlossomsDropFromLeaves", "all", true, "Whether acacia blossoms should drop from blocks tagged with #alexsmobs:drops_acacia_blossoms");
        acaciaBlossomChance = buildInt(builder, "acaciaBlossomChance", "all", AMConfig.acaciaBlossomChance, 0, Integer.MAX_VALUE, "1 out of this number chance for leaves to drop an acacia when broken. Fortune is automatically factored in");
        wanderingTraderOffers = buildBoolean(builder, "wanderingTraderOffers", "all", true, "Whether wandering traders offer items like acacia blossoms, mosquito larva, crocodile egg, etc.");
        mungusBiomeTransformationType = buildInt(builder, "mungusBiomeTransformationType", "all", AMConfig.mungusBiomeTransformationType, 0, 2, "0 = no mungus biome transformation. 1 = mungus changes blocks, but not chunk's biome. 2 = mungus transforms blocks and biome of chunk.");
        mungusBiomeMatches = builder.comment("List of all mungus mushrooms, biome transformations and surface blocks. Each is seperated by a |. Add an entry with a block registry name, biome registry name, and block registry name(for the ground).").defineList("mungusBiomeMatches", AMConfig.mungusBiomeMatches, o -> o instanceof String);
        limitGusterSpawnsToWeather = buildBoolean(builder, "limitGusterSpawnsToWeather", "all", true, "Whether guster spawns are limited to when it is raining/thundering.");
        warpedMoscoTransformation = buildBoolean(builder, "warpedMoscoTransformation", "all", true, "Whether Crimson Mosquitoes can transform into Warped Moscos if attacking a Mungus or any listed creature.");
        warpedMoscoMobTriggers = builder.comment("List of extra(non mungus) mobs that will trigger a crimson mosquito to become a warped mosquito. Ex: \"minecraft:mooshroom\", \"alexsmobs:warped_toad\"").defineList("warpedMoscoMobTriggers", Lists.newArrayList(""), o -> o instanceof String);
        straddleboardEnchants = buildBoolean(builder, "straddleboardEnchants", "all", true, "True if straddleboard enchants are enabled.");
        straddleboardBaseColor = buildInt(builder, "straddleboardBaseColor", "all", 0xFFFFFF, 0, 0xFFFFFF, "Colour tint of the straddleboard's wooden base, as a decimal RGB value (0xFFFFFF = 16777215 = untinted). Together with straddleboardPanelColor this controls how much the board stands out against its background - raise the base and lower the panel, or vice versa, if a resource pack makes the board hard to see.");
        straddleboardPanelColor = buildInt(builder, "straddleboardPanelColor", "all", 0xADC3D7, 0, 0xFFFFFF, "Colour of the straddleboard's grey panel when the board has not been dyed, as a decimal RGB value (the default 0xADC3D7 = 11387351). Dyed boards keep their dye. Purely visual and read on whichever machine is drawing, so it can differ between a client and the server it is connected to.");
        emuTargetSkeletons = buildBoolean(builder, "emuTargetSkeletons", "all", true, "Whether emu should target skeletons.");
        emuPantsDodgeChance = buildDouble(builder, "emuPantsDodgeChance", "all", 0.45D, 0D, 1D, "Percent chance for emu leggings to dodge projectile attacks.");
        cachalotDestruction = buildBoolean(builder, "cachalotDestruction", "all", true, "Whether cachalots can destroy wood blocks if angry.");
        cachalotVolume = buildDouble(builder, "cachalotVolume", "all", 3D, 0D, 10D, "Relative volume of cachalot whales compared to other animals. Note that irl they are the loudest animal. Turn this down if you find their clicks annoying.");
        leafcutterAntFungusGrowChance = buildDouble(builder, "leafcutterAntFungusGrowChance", "all", 0.3D, 0D, 1D, "Percent chance for fungus to grow per each leaf a leafcutter ant returns to the colony.");
        leafcutterAntRepopulateFeedings = buildInt(builder, "leafcutterAntRepopulateFeedings", "all", AMConfig.leafcutterAntRepopulateFeedings, 2, 100000,"How many feedings of leaves does a leafcutter colony need in order to regain a worker ant, if below half the max members.");
        leafcutterAntColonySize = buildInt(builder, "leafcutterAntColonySize", "all", AMConfig.leafcutterAntColonySize, 2, 100000,"Max number of ant entities allowed inside a leafcutter anthill.");
        leafcutterAntBreakLeavesChance = buildDouble(builder, "leafcutterAntBreakLeavesChance", "all", 0.2D, 0D, 1D, "Percent chance for leafcutter ants to break leaves blocks when harvesting. Set to zero so that they can not break any blocks.");
        falconryTeleportsBack = buildBoolean(builder, "falconryTeleportsBack", "all", false, "Makes eagles teleport back to their owner if they get stuck during controlled flight. Useful for when playing with the Optifine mod, since this mod is the fault of many issues with the falconry system.");
        fireproofTarantulaHawk = buildBoolean(builder, "fireproofTarantulaHawk", "all", false, "Makes Tarantula Hawks fireproof, perfect if you also want these guys to spawn in the nether.");
        voidWormSpawnDimensions = builder.comment("List of dimensions in which spawning void worms via mysterious worm items is allowed.").defineList("voidWormSpawnDimensions", Lists.newArrayList("minecraft:the_end"), o -> o instanceof String);
        voidWormDamageModifier = buildDouble(builder, "voidWormDamageModifier", "all", 1.0D, 0D, 100D, "All void worm damage is scaled to this.");
        voidWormMaxHealth = buildDouble(builder, "voidWormMaxHealth", "all", 160.0D, 0D, 1000000D, "Max Health of the void worm boss.");
        voidWormSummonable = buildBoolean(builder, "voidWormSummonable", "all", true, "Whether the void worm boss is summonable or not, via the mysterious worm item.");
        seagullStealing = buildBoolean(builder, "seagullStealing", "all", true, "Whether seagulls should steal food out of players' hotbar slots.");
        seagullStealingBlacklist = builder.comment("List of items that seagulls cannot take from players.").defineList("seagullStealingBlacklist", Lists.newArrayList(), o -> o instanceof String);
        clingingFlipEffect = buildBoolean(builder, "clingingFlipEffect", "all", false, "Whether the Clinging Potion effect should flip the screen. Warning: may cause nausea.");
        tusklinShoesBarteringChance = buildDouble(builder, "tusklinShoesBarteringChance", "all", 0.025F, 0D, 1.0F, "Percent chance of getting Pigshoes from Piglin Bartering. Set to zero to disable.");
        rainbowGlassFidelity = buildDouble(builder, "rainbowGlassFidelity", "all", 16.0F, 1.0F, 10000.0F, "The visual zoom of the rainbow pattern on the rainbow glass block. Higher number = bigger pattern.");
        bunfungusTransformation = buildBoolean(builder, "bunfungusTransformation", "all", true, "Whether Rabbits can transform into Bunfungus if fed Mungal spores.");
        addLootToChests = buildBoolean(builder, "addLootToChests", "all", true, "True if some Alex's Mobs items should spawn in loot chests.");
        transmutationBlacklist = builder.comment("List of items that cannot be put in a Transmuting Table.").defineList("transmutationBlacklist", Lists.newArrayList("minecraft:beacon"), o -> o instanceof String);
        limitTransmutingToLootTables = buildBoolean(builder, "limitTransmutingToLootTables", "all", false, "True if transmutation tables should not have the ability to pick up new items to transmute, and only give options from the loot tables.");
        transmutingTableExplodes = buildBoolean(builder, "transmutingTableExplodes", "all", true, "True if transmutation tables can explode when broken.");
        transmutingExperienceCost = buildInt(builder, "transmutingExperienceCost", "all", AMConfig.transmutingExperienceCost, 0, 100000,"The experience, in levels, that each transmutation of a stack takes in the transmuting table.");
        transmutingWeightAddStep = buildDouble(builder, "transmutingWeightAddStep", "all", 3.0F, 1.0F, 10000.0F, "The step value multiplied by the log of the stack size when transmuting an item, used to determine its weight for appearing in future transmutation possibilities. Higher number = more likely to appear.");
        transmutingWeightRemoveStep = buildDouble(builder, "transmutingWeightRemoveStep", "all", 4.0F, 1.0F, 10000.0F, "The step value that an item looses when selecting it as the transmutation result. Keep this number higher than the one above for balance reasons. Higher number = less likely to appear after transmuting multiple times.");
        skreechersSummonWarden = buildBoolean(builder, "skreechersSummonWarden", "all", true, "True if skreechers can summon a new warden, when applicable.");
        underminerDisappearDistance = buildDouble(builder, "underminerDisappearDistance", "all", 8.0F, 1.0F, 10000.0F, "The distance in blocks that will cause an underminer to dissapear when approached by a player.");
        builder.pop();
        builder.push("spawning");
        grizzlyBearSpawnWeight = buildInt(builder, "grizzlyBearSpawnWeight", "spawns", AMConfig.grizzlyBearSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        grizzlyBearSpawnRolls = buildInt(builder, "grizzlyBearSpawnRolls", "spawns", AMConfig.grizzlyBearSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        roadrunnerSpawnWeight = buildInt(builder, "roadrunnerSpawnWeight", "spawns", AMConfig.roadrunnerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        roadrunnerSpawnRolls = buildInt(builder, "roadrunnerSpawnRolls", "spawns", AMConfig.roadrunnerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        boneSerpentSpawnWeight = buildInt(builder, "boneSerpentSpawnWeight", "spawns", AMConfig.boneSerpentSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        boneSeprentSpawnRolls = buildInt(builder, "boneSeprentSpawnRolls", "spawns", AMConfig.boneSeprentSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        gazelleSpawnWeight = buildInt(builder, "gazelleSpawnWeight", "spawns", AMConfig.gazelleSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        gazelleSpawnRolls = buildInt(builder, "gazelleSpawnRolls", "spawns", AMConfig.gazelleSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        crocodileSpawnWeight = buildInt(builder, "crocodileSpawnWeight", "spawns", AMConfig.crocodileSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        crocSpawnRolls = buildInt(builder, "crocSpawnRolls", "spawns", AMConfig.crocSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        flySpawnWeight = buildInt(builder, "flySpawnWeight", "spawns", AMConfig.flySpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        flySpawnRolls = buildInt(builder, "flySpawnRolls", "spawns", AMConfig.flySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        hummingbirdSpawnWeight = buildInt(builder, "hummingbirdSpawnWeight", "spawns", AMConfig.hummingbirdSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        hummingbirdSpawnRolls = buildInt(builder, "hummingbirdSpawnRolls", "spawns", AMConfig.flySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        orcaSpawnWeight = buildInt(builder, "orcaSpawnWeight", "spawns", AMConfig.orcaSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        orcaSpawnRolls = buildInt(builder, "orcaSpawnRolls", "spawns", AMConfig.orcaSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        sunbirdSpawnWeight = buildInt(builder, "sunbirdSpawnWeight", "spawns", AMConfig.sunbirdSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        sunbirdSpawnRolls = buildInt(builder, "sunbirdSpawnRolls", "spawns", AMConfig.sunbirdSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        gorillaSpawnWeight = buildInt(builder, "gorillaSpawnWeight", "spawns", AMConfig.gorillaSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        gorillaSpawnRolls = buildInt(builder, "gorillaSpawnRolls", "spawns", AMConfig.gorillaSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        crimsonMosquitoSpawnWeight = buildInt(builder, "crimsonMosquitoSpawnWeight", "spawns", AMConfig.crimsonMosquitoSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        crimsonMosquitoSpawnRolls = buildInt(builder, "crimsonMosquitoSpawnRolls", "spawns", AMConfig.crimsonMosquitoSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        rattlesnakeSpawnWeight = buildInt(builder, "rattlesnakeSpawnWeight", "spawns", AMConfig.rattlesnakeSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        rattlesnakeSpawnRolls = buildInt(builder, "rattlesnakeSpawnRolls", "spawns", AMConfig.rattlesnakeSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        endergradeSpawnWeight = buildInt(builder, "endergradeSpawnWeight", "spawns", AMConfig.endergradeSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        endergradeSpawnRolls = buildInt(builder, "endergradeSpawnRolls", "spawns", AMConfig.endergradeSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        hammerheadSharkSpawnWeight = buildInt(builder, "hammerheadSharkSpawnWeight", "spawns", AMConfig.hammerheadSharkSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        hammerheadSharkSpawnRolls = buildInt(builder, "hammerheadSharkSpawnRolls", "spawns", AMConfig.hammerheadSharkSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        lobsterSpawnWeight = buildInt(builder, "lobsterSpawnWeight", "spawns", AMConfig.lobsterSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        lobsterSpawnRolls = buildInt(builder, "lobsterSpawnRolls", "spawns", AMConfig.lobsterSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        komodoDragonSpawnWeight = buildInt(builder, "komodoDragonSpawnWeight", "spawns", AMConfig.komodoDragonSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        komodoDragonSpawnRolls = buildInt(builder, "komodoDragonSpawnRolls", "spawns", AMConfig.komodoDragonSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        capuchinMonkeySpawnWeight = buildInt(builder, "capuchinMonkeySpawnWeight", "spawns", AMConfig.capuchinMonkeySpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        capuchinMonkeySpawnRolls = buildInt(builder, "capuchinMonkeySpawnRolls", "spawns", AMConfig.capuchinMonkeySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        caveCentipedeSpawnWeight = buildInt(builder, "caveCentipedeSpawnWeight", "spawns", AMConfig.caveCentipedeSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        caveCentipedeSpawnRolls = buildInt(builder, "caveCentipedeSpawnRolls", "spawns", AMConfig.caveCentipedeSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        warpedToadSpawnWeight = buildInt(builder, "warpedToadSpawnWeight", "spawns", AMConfig.warpedToadSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        warpedToadSpawnRolls = buildInt(builder, "warpedToadSpawnRolls", "spawns", AMConfig.warpedToadSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mooseSpawnWeight = buildInt(builder, "mooseSpawnWeight", "spawns", AMConfig.mooseSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mooseSpawnRolls = buildInt(builder, "mooseSpawnRolls", "spawns", AMConfig.mooseSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mimicubeSpawnWeight = buildInt(builder, "mimicubeSpawnWeight", "spawns", AMConfig.mimicubeSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mimicubeSpawnRolls = buildInt(builder, "mimicubeSpawnRolls", "spawns", AMConfig.mimicubeSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        raccoonSpawnWeight = buildInt(builder, "raccoonSpawnWeight", "spawns", AMConfig.raccoonSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        raccoonSpawnRolls = buildInt(builder, "raccoonSpawnRolls", "spawns", AMConfig.raccoonSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        blobfishSpawnWeight = buildInt(builder, "blobfishSpawnWeight", "spawns", AMConfig.blobfishSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        blobfishSpawnRolls = buildInt(builder, "blobfishSpawnRolls", "spawns", AMConfig.blobfishSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        sealSpawnWeight = buildInt(builder, "sealSpawnWeight", "spawns", AMConfig.sealSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        sealSpawnRolls = buildInt(builder, "sealSpawnRolls", "spawns", AMConfig.sealSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        cockroachSpawnWeight = buildInt(builder, "cockroachSpawnWeight", "spawns", AMConfig.cockroachSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        cockroachSpawnRolls = buildInt(builder, "cockroachSpawnRolls", "spawns", AMConfig.cockroachSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        shoebillSpawnWeight = buildInt(builder, "shoebillSpawnWeight", "spawns", AMConfig.shoebillSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        shoebillSpawnRolls = buildInt(builder, "shoebillSpawnRolls", "spawns", AMConfig.shoebillSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        elephantSpawnWeight = buildInt(builder, "elephantSpawnWeight", "spawns", AMConfig.elephantSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        elephantSpawnRolls = buildInt(builder, "elephantSpawnRolls", "spawns", AMConfig.elephantSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        soulVultureSpawnWeight = buildInt(builder, "soulVultureSpawnWeight", "spawns", AMConfig.soulVultureSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        soulVultureSpawnRolls = buildInt(builder, "soulVultureSpawnRolls", "spawns", AMConfig.soulVultureSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        snowLeopardSpawnWeight = buildInt(builder, "snowLeopardSpawnWeight", "spawns", AMConfig.snowLeopardSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        snowLeopardSpawnRolls = buildInt(builder, "snowLeopardSpawnRolls", "spawns", AMConfig.snowLeopardSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        spectreSpawnWeight = buildInt(builder, "spectreSpawnWeight", "spawns", AMConfig.spectreSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        spectreSpawnRolls = buildInt(builder, "spectreSpawnRolls", "spawns", AMConfig.spectreSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        crowSpawnWeight = buildInt(builder, "crowSpawnWeight", "spawns", AMConfig.crowSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        crowSpawnRolls = buildInt(builder, "crowSpawnRolls", "spawns", AMConfig.crowSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        alligatorSnappingTurtleSpawnWeight = buildInt(builder, "alligatorSnappingTurtleSpawnWeight", "spawns", AMConfig.alligatorSnappingTurtleSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        alligatorSnappingTurtleSpawnRolls = buildInt(builder, "alligatorSnappingTurtleSpawnRolls", "spawns", AMConfig.alligatorSnappingTurtleSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mungusSpawnWeight = buildInt(builder, "mungusSpawnWeight", "spawns", AMConfig.mungusSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mungusSpawnRolls = buildInt(builder, "mungusSpawnRolls", "spawns", AMConfig.mungusSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mantisShrimpSpawnWeight = buildInt(builder, "mantisShrimpSpawnWeight", "spawns", AMConfig.mantisShrimpSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mantisShrimpSpawnRolls = buildInt(builder, "mantisShrimpSpawnRolls", "spawns", AMConfig.mantisShrimpSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        gusterSpawnWeight = buildInt(builder, "gusterSpawnWeight", "spawns", AMConfig.gusterSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        gusterSpawnRolls = buildInt(builder, "gusterSpawnRolls", "spawns", AMConfig.gusterSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        warpedMoscoSpawnWeight = buildInt(builder, "warpedMoscoSpawnWeight", "spawns", AMConfig.warpedMoscoSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn. NOTE: By default the warped mosco doesn't spawn in any biomes.");
        warpedMoscoSpawnRolls = buildInt(builder, "warpedMoscoSpawnRolls", "spawns", AMConfig.warpedMoscoSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        straddlerSpawnWeight = buildInt(builder, "straddlerSpawnWeight", "spawns", AMConfig.straddlerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        straddlerSpawnRolls = buildInt(builder, "straddlerSpawnRolls", "spawns", AMConfig.straddlerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        stradpoleSpawnWeight = buildInt(builder, "stradpoleSpawnWeight", "spawns", AMConfig.stradpoleSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        stradpoleSpawnRolls = buildInt(builder, "stradpoleSpawnRolls", "spawns", AMConfig.stradpoleSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        emuSpawnWeight = buildInt(builder, "emuSpawnWeight", "spawns", AMConfig.emuSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        emuSpawnRolls = buildInt(builder, "emuSpawnRolls", "spawns", AMConfig.emuSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        platypusSpawnWeight = buildInt(builder, "platypusSpawnWeight", "spawns", AMConfig.platypusSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        platypusSpawnRolls = buildInt(builder, "platypusSpawnRolls", "spawns", AMConfig.platypusSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        dropbearSpawnWeight = buildInt(builder, "dropbearSpawnWeight", "spawns", AMConfig.dropbearSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        dropbearSpawnRolls = buildInt(builder, "dropbearSpawnRolls", "spawns", AMConfig.dropbearSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        tasmanianDevilSpawnWeight = buildInt(builder, "tasmanianDevilSpawnWeight", "spawns", AMConfig.tasmanianDevilSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        tasmanianDevilSpawnRolls = buildInt(builder, "tasmanianDevilSpawnRolls", "spawns", AMConfig.tasmanianDevilSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        kangarooSpawnWeight = buildInt(builder, "kangarooSpawnWeight", "spawns", AMConfig.kangarooSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        kangarooSpawnRolls = buildInt(builder, "kangarooSpawnRolls", "spawns", AMConfig.kangarooSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        cachalotWhaleSpawnWeight = buildInt(builder, "cachalotWhaleSpawnWeight", "spawns", AMConfig.cachalotWhaleSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        cachalotWhaleSpawnRolls = buildInt(builder, "cachalotWhaleSpawnRolls", "spawns", AMConfig.cachalotWhaleSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        enderiophageSpawnWeight = buildInt(builder, "enderiophageSpawnWeight", "spawns", AMConfig.enderiophageSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        enderiophageSpawnRolls = buildInt(builder, "enderiophageSpawnRolls", "spawns", AMConfig.enderiophageSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        baldEagleSpawnWeight = buildInt(builder, "baldEagleSpawnWeight", "spawns", AMConfig.baldEagleSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        baldEagleSpawnRolls = buildInt(builder, "baldEagleSpawnRolls", "spawns", AMConfig.baldEagleSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        tigerSpawnWeight = buildInt(builder, "tigerSpawnWeight", "spawns", AMConfig.tigerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        tigerSpawnRolls = buildInt(builder, "tigerSpawnRolls", "spawns", AMConfig.tigerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        tarantulaHawkSpawnWeight = buildInt(builder, "tarantulaHawkSpawnWeight", "spawns", AMConfig.tarantulaHawkSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        tarantulaHawkSpawnRolls = buildInt(builder, "tarantulaHawkSpawnRolls", "spawns", AMConfig.tarantulaHawkSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        voidWormSpawnWeight = buildInt(builder, "voidWormSpawnWeight", "spawns", AMConfig.voidWormSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        voidWormSpawnRolls = buildInt(builder, "voidWormSpawnRolls", "spawns", AMConfig.voidWormSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        frilledSharkSpawnWeight = buildInt(builder, "frilledSharkSpawnWeight", "spawns", AMConfig.frilledSharkSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        frilledSharkSpawnRolls = buildInt(builder, "frilledSharkSpawnRolls", "spawns", AMConfig.frilledSharkSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mimicOctopusSpawnWeight = buildInt(builder, "mimicOctopusSpawnWeight", "spawns", AMConfig.mimicOctopusSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mimicOctopusSpawnRolls = buildInt(builder, "mimicOctopusSpawnRolls", "spawns", AMConfig.mimicOctopusSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        seagullSpawnWeight = buildInt(builder, "seagullSpawnWeight", "spawns", AMConfig.seagullSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        seagullSpawnRolls = buildInt(builder, "seagullSpawnRolls", "spawns", AMConfig.seagullSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        froststalkerSpawnWeight = buildInt(builder, "froststalkerSpawnWeight", "spawns", AMConfig.froststalkerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        froststalkerSpawnRolls = buildInt(builder, "froststalkerSpawnRolls", "spawns", AMConfig.froststalkerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        tusklinSpawnWeight = buildInt(builder, "tusklinSpawnWeight", "spawns", AMConfig.tusklinSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        tusklinSpawnRolls = buildInt(builder, "tusklinSpawnRolls", "spawns", AMConfig.tusklinSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        laviathanSpawnWeight = buildInt(builder, "laviathanSpawnWeight", "spawns", AMConfig.laviathanSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        laviathanSpawnRolls = buildInt(builder, "laviathanSpawnRolls", "spawns", AMConfig.laviathanSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        cosmawSpawnWeight = buildInt(builder, "cosmawSpawnWeight", "spawns", AMConfig.cosmawSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        cosmawSpawnRolls = buildInt(builder, "cosmawSpawnRolls", "spawns", AMConfig.cosmawSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        toucanSpawnWeight = buildInt(builder, "toucanSpawnWeight", "spawns", AMConfig.toucanSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        toucanSpawnRolls = buildInt(builder, "toucanSpawnRolls", "spawns", AMConfig.toucanSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        manedWolfSpawnWeight = buildInt(builder, "manedWolfSpawnWeight", "spawns", AMConfig.manedWolfSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        manedWolfSpawnRolls = buildInt(builder, "manedWolfSpawnRolls", "spawns", AMConfig.manedWolfSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        anacondaSpawnWeight = buildInt(builder, "anacondaSpawnWeight", "spawns", AMConfig.anacondaSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        anacondaSpawnRolls = buildInt(builder, "anacondaSpawnRolls", "spawns", AMConfig.anacondaSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        anteaterSpawnWeight = buildInt(builder, "anteaterSpawnWeight", "spawns", AMConfig.anteaterSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        anteaterSpawnRolls = buildInt(builder, "anteaterSpawnRolls", "spawns", AMConfig.anteaterSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        rockyRollerSpawnWeight = buildInt(builder, "rockyRollerSpawnWeight", "spawns", AMConfig.rockyRollerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        rockyRollerSpawnRolls = buildInt(builder, "rockyRollerSpawnRolls", "spawns", AMConfig.rockyRollerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        flutterSpawnWeight = buildInt(builder, "flutterSpawnWeight", "spawns", AMConfig.flutterSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        flutterSpawnRolls = buildInt(builder, "flutterSpawnRolls", "spawns", AMConfig.flutterSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        geladaMonkeySpawnWeight = buildInt(builder, "geladaMonkeySpawnWeight", "spawns", AMConfig.geladaMonkeySpawnWeight, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        geladaMonkeySpawnRolls = buildInt(builder, "geladaMonkeySpawnRolls", "spawns", AMConfig.geladaMonkeySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        jerboaSpawnWeight = buildInt(builder, "jerboaSpawnWeight", "spawns", AMConfig.jerboaSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        jerboaSpawnRolls = buildInt(builder, "jerboaSpawnRolls", "spawns", AMConfig.jerboaSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        terrapinSpawnWeight = buildInt(builder, "terrapinSpawnWeight", "spawns", AMConfig.terrapinSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        terrapinSpawnRolls = buildInt(builder, "terrapinSpawnRolls", "spawns", AMConfig.terrapinSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        combJellySpawnWeight = buildInt(builder, "combJellySpawnWeight", "spawns", AMConfig.combJellySpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        combJellySpawnRolls = buildInt(builder, "combJellySpawnRolls", "spawns", AMConfig.combJellySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        cosmicCodSpawnWeight = buildInt(builder, "cosmicCodSpawnWeight", "spawns", AMConfig.cosmicCodSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        cosmicCodSpawnRolls = buildInt(builder, "cosmicCodSpawnRolls", "spawns", AMConfig.cosmicCodSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        bunfungusSpawnWeight = buildInt(builder, "bunfungusSpawnWeight", "spawns", AMConfig.bunfungusSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        bunfungusSpawnRolls = buildInt(builder, "bunfungusSpawnRolls", "spawns", AMConfig.bunfungusSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        bisonSpawnWeight = buildInt(builder, "bisonSpawnWeight", "spawns", AMConfig.bisonSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        bisonSpawnRolls = buildInt(builder, "bisonSpawnRolls", "spawns", AMConfig.bisonSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        giantSquidSpawnWeight = buildInt(builder, "giantSquidSpawnWeight", "spawns", AMConfig.giantSquidSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        giantSquidSpawnRolls = buildInt(builder, "giantSquidSpawnRolls", "spawns", AMConfig.giantSquidSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        devilsHolePupfishSpawnWeight = buildInt(builder, "devilsHolePupfishSpawnWeight", "spawns", AMConfig.devilsHolePupfishSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn (NOTE: this mob spawns are restricted exclusively to one chunk, see below)");
        devilsHolePupfishSpawnRolls = buildInt(builder, "devilsHolePupfishSpawnRolls", "spawns", AMConfig.devilsHolePupfishSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning (NOTE: this mob spawns are restricted exclusively to one chunk, see below)");
        catfishSpawnWeight = buildInt(builder, "catfishSpawnWeight", "spawns", AMConfig.catfishSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        catfishSpawnRolls = buildInt(builder, "catfishSpawnRolls", "spawns", AMConfig.catfishSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        flyingFishSpawnWeight = buildInt(builder, "flyingFishSpawnWeight", "spawns", AMConfig.flyingFishSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        flyingFishSpawnRolls = buildInt(builder, "flyingFishSpawnRolls", "spawns", AMConfig.flyingFishSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        skelewagSpawnWeight = buildInt(builder, "skelewagSpawnWeight", "spawns", AMConfig.skelewagSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        skelewagSpawnRolls = buildInt(builder, "skelewagSpawnRolls", "spawns", AMConfig.skelewagSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        rainFrogSpawnWeight = buildInt(builder, "rainFrogSpawnWeight", "spawns", AMConfig.rainFrogSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        rainFrogSpawnRolls = buildInt(builder, "rainFrogSpawnRolls", "spawns", AMConfig.rainFrogSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        potooSpawnWeight = buildInt(builder, "potooSpawnWeight", "spawns", AMConfig.potooSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        potooSpawnRolls = buildInt(builder, "potooSpawnRolls", "spawns", AMConfig.potooSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        mudskipperSpawnWeight = buildInt(builder, "mudskipperSpawnWeight", "spawns", AMConfig.mudskipperSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        mudskipperSpawnRolls = buildInt(builder, "mudskipperSpawnRolls", "spawns", AMConfig.mudskipperSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        rhinocerosSpawnWeight = buildInt(builder, "rhinocerosSpawnWeight", "spawns", AMConfig.rhinocerosSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        rhinocerosSpawnRolls = buildInt(builder, "rhinocerosSpawnRolls", "spawns", AMConfig.rhinocerosSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        sugarGliderSpawnWeight = buildInt(builder, "sugarGliderSpawnWeight", "spawns", AMConfig.sugarGliderSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        sugarGliderSpawnRolls = buildInt(builder, "sugarGliderSpawnRolls", "spawns", AMConfig.sugarGliderSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        farseerSpawnWeight = buildInt(builder, "farseerSpawnWeight", "spawns", AMConfig.farseerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        farseerSpawnRolls = buildInt(builder, "farseerSpawnRolls", "spawns", AMConfig.farseerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        skreecherSpawnWeight = buildInt(builder, "skreecherSpawnWeight", "spawns", AMConfig.skreecherSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        skreecherSpawnRolls = buildInt(builder, "skreecherSpawnRolls", "spawns", AMConfig.skreecherSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        underminerSpawnWeight = buildInt(builder, "underminerSpawnWeight", "spawns", AMConfig.underminerSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        underminerSpawnRolls = buildInt(builder, "underminerSpawnRolls", "spawns", AMConfig.underminerSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        murmurSpawnWeight = buildInt(builder, "murmurSpawnWeight", "spawns", AMConfig.murmurSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        murmurSpawnRolls = buildInt(builder, "murmurSpawnRolls", "spawns", AMConfig.murmurSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        skunkSpawnWeight = buildInt(builder, "skunkSpawnWeight", "spawns", AMConfig.skunkSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        skunkSpawnRolls = buildInt(builder, "skunkSpawnRolls", "spawns", AMConfig.skunkSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        bananaSlugSpawnWeight = buildInt(builder, "bananaSlugSpawnWeight", "spawns", AMConfig.bananaSlugSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        bananaSlugSpawnRolls = buildInt(builder, "bananaSlugSpawnRolls", "spawns", AMConfig.bananaSlugSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        blueJaySpawnWeight = buildInt(builder, "blueJaySpawnWeight", "spawns", AMConfig.blueJaySpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        blueJaySpawnRolls = buildInt(builder, "blueJaySpawnRolls", "spawns", AMConfig.blueJaySpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        caimanSpawnWeight = buildInt(builder, "caimanSpawnWeight", "spawns", AMConfig.caimanSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        caimanSpawnRolls = buildInt(builder, "caimanSpawnRolls", "spawns", AMConfig.caimanSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        triopsSpawnWeight = buildInt(builder, "triopsSpawnWeight", "spawns", AMConfig.triopsSpawnWeight, 0, 1000, "Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn");
        triopsSpawnRolls = buildInt(builder, "triopsSpawnRolls", "spawns", AMConfig.triopsSpawnRolls, 0, Integer.MAX_VALUE, "Random roll chance to enable mob spawning. Higher number = lower chance of spawning");
        builder.pop();
        builder.push("uniqueSpawning");
        caveCentipedeSpawnHeight = buildInt(builder, "caveCentipedeSpawnHeight", "all", AMConfig.caveCentipedeSpawnHeight, -64, 320, "Maximum world y-level that cave centipedes can spawn at");
        blobfishSpawnHeight = buildInt(builder, "blobfishSpawnHeight", "all", AMConfig.blobfishSpawnHeight, -64, 320, "Maximum world y-level that blobfish can spawn at");
        beachedCachalotWhales = buildBoolean(builder, "beachedCachalotWhales", "uniqueSpawning", true, "Whether to enable beached cachalot whales to spawn on beaches during thunder storms.");
        beachedCachalotWhaleSpawnChance = buildInt(builder, "beachedCachalotWhaleSpawnChance", "uniqueSpawning", AMConfig.beachedCachalotWhaleSpawnChance, 0, 100, "Percent chance increase for each failed attempt to spawn a beached cachalot whale. Higher value = more spawns.");
        beachedCachalotWhaleSpawnDelay = buildInt(builder, "beachedCachalotWhaleSpawnDelay", "uniqueSpawning", AMConfig.beachedCachalotWhaleSpawnDelay, 0, Integer.MAX_VALUE, "Delay (in ticks) between attempts to spawn beached cachalot whales. Default is a single day. Works like wandering traders.");
        leafcutterAnthillSpawnChance = buildDouble(builder, "leafcutterAnthillSpawnChance", "uniqueSpawning", AMConfig.leafcutterAnthillSpawnChance, 0D, 1D, "Percent chance for leafcutter anthills to spawn as world gen in each chunk. Set to zero to disable spawning.");
        geladaMonkeySpawnHeight = buildInt(builder, "geladaMonkeySpawnRolls", "spawns", AMConfig.geladaMonkeySpawnRolls, -64, 320, "Minimum world y-level that gelada monkeys can spawn at");
        restrictPupfishSpawns = buildBoolean(builder, "restrictPupfishSpawns", "uniqueSpawning", true, "Whether to restrict all pupfish spawns to one chunk (similar to real life) or have them only obey their spawn config.");
        pupfishChunkSpawnDistance = buildInt(builder, "pupfishChunkSpawnDistance", "uniqueSpawning", AMConfig.pupfishChunkSpawnDistance, 2, 1000000000, "The maximum distance a pupfish spawn chunk is from world spawn(0, 0) in blocks.");
        restrictSkelewagSpawns = buildBoolean(builder, "restrictSkelewagSpawns", "uniqueSpawning", true, "Whether to restrict all skelewag spawns to shipwreck structures.");
        restrictFarseerSpawns = buildBoolean(builder, "restrictFarseerSpawns", "uniqueSpawning", true, "Whether to restrict all farseer spawns to near the world border.");
        restrictUnderminerSpawns = buildBoolean(builder, "restrictUnderminerSpawns", "uniqueSpawning", true, "Whether to restrict all underminer spawns to abandoned mineshafts.");
        farseerBorderSpawnDistance = buildInt(builder, "farseerBorderSpawnDistance", "uniqueSpawning", AMConfig.farseerBorderSpawnDistance, 2, 1000000000, "The maximum distance a farseer can spawn from the world border.");
        murmurSpawnHeight = buildInt(builder, "murmurSpawnHeight", "all", AMConfig.murmurSpawnHeight, -64, 320, "Maximum world y-level that murmur can spawn at");
        builder.pop();
        builder.push("dangerZone");
        superSecretSettings = buildBoolean(builder, "superSecretSettings", "dangerZone", false, "Its been so long...");
        pathfindingThreads = buildInt(builder, "pathfindingThreads", "dangerZone", AMConfig.pathfindingThreads, 1, 100,"How many cpu cores some mobs(elephants, leafcutter ants, bison etc) should utilize when pathing. Bigger number = less impact on TPS");
        builder.pop();
    }

    private static CodxSettings.BooleanValue buildBoolean(CodxSettings.Builder builder, String name, String catagory, boolean defaultValue, String comment) {
        return builder.comment(comment).translation(name).define(name, defaultValue);
    }

    private static CodxSettings.IntValue buildInt(CodxSettings.Builder builder, String name, String catagory, int defaultValue, int min, int max, String comment) {
        return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
    }

    private static CodxSettings.DoubleValue buildDouble(CodxSettings.Builder builder, String name, String catagory, double defaultValue, double min, double max, String comment) {
        return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
    }
}
